ci: update workflow for secret-manager-apply

diff --git a/.github/workflows/secret-manager-apply.yaml b/.github/workflows/secret-manager-apply.yaml
--- a/.github/workflows/secret-manager-apply.yaml
+++ b/.github/workflows/secret-manager-apply.yaml
@@ -32,21 +32,21 @@ env:
   AWS_REGION: ${{ vars.AWS_REGION }}
   STATE_BUCKET: ${{ vars.STATE_BUCKET }}
   NICKNAME: secretmanager
+  WORKING_DIRECTORY: secret-manager
   # Inputs
   ENVIRONMENT: ${{ inputs.environment }}
   DESTROY: ${{ inputs.destroy }}
-  WORKING_DIRECTORY: secret-manager
   # Terraform Variables are prefixed with TF_VAR
   TF_VAR_aws_region: ${{ vars.AWS_REGION }}
   TF_VAR_database_password: ${{ secrets.TF_VAR_DATABASE_PASSWORD }}
 
 jobs:
-  plan:
-    name: Terraform Plan
+  plan-apply:
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
-    outputs:
-      exitcode: ${{ steps.tf-plan.outputs.exitcode }}
+    env:
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
 
     steps:
       # Checkout the repository to the GitHub Actions runner
@@ -58,7 +58,12 @@ jobs:
           role-to-assume: ${{ env.ROLE_TO_ASSUME }}
           role-session-name: ${{ env.ROLE_SESSION_NAME }}
           aws-region: ${{ env.AWS_REGION }}
-
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: ${{ env.TF_VERSION }}
+          # https://github.com/hashicorp/setup-terraform/issues/152
+          terraform_wrapper: false
       # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
       - name: Terraform Init
         working-directory: ${{ env.WORKING_DIRECTORY }}
@@ -68,27 +73,23 @@ jobs:
           -backend-config="region=$AWS_REGION" \
           -backend-config="key=$NICKNAME/$ENVIRONMENT/$AWS_REGION/terraform.tfstate"
 
-      # Checks that all Terraform configuration files adhere to a canonical format
-      # Will fail the build if not
-      - name: Terraform Format
-        run: terraform fmt -check
-
       # Generates an execution plan for Terraform
       # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
       - name: Terraform Plan
         id: tf-plan
         working-directory: ${{ env.WORKING_DIRECTORY }}
         run: |
-          export exitcode=0
+          set +e # allow the workflow to continue following steps even if the `terraform` execution failed
           if [ "$DESTROY" = "true" ]; then
             echo "This is a destroy plan"
-
-            terraform plan -destroy -var-file $(pwd)/tf_$ENVIRONMENT.tfvars \
-            -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+            export options="-destroy"
           else
-            terraform plan -var-file $(pwd)/tf_$ENVIRONMENT.tfvars \
-            -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+            export options=""
           fi
+
+          terraform plan -detailed-exitcode $options -var-file $(pwd)/tf_$ENVIRONMENT.tfvars -out tfplan
+          exitcode=$?
+          echo exitcode = $exitcode
 
           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
@@ -98,14 +99,7 @@ jobs:
           else
             exit 0
           fi
-      # Save plan to artifacts
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v4
-        with:
-          name: tfplan
-          path: ${{ env.WORKING_DIRECTORY }}/tfplan
 
-      # Create string output of Terraform Plan
       - name: Create String Output
         id: tf-plan-string
         working-directory: ${{ env.WORKING_DIRECTORY }}
@@ -123,18 +117,33 @@ jobs:
           echo "</details>" >> $GITHUB_OUTPUT
           echo "${delimiter}" >> $GITHUB_OUTPUT
 
-      # Publish Terraform Plan as task summary
       - name: Publish Terraform Plan to Task Summary
         env:
           SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
         run: |
           echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
 
-  apply:
-    needs: [plan]
-    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-apply-reusable.yaml@main
-    secrets: inherit
-    with:
-      environment: ${{ inputs.environment }}
-      nickname: secretmanager
-      working-directory: secret-manager
+      - name: Terraform Apply
+        if: ${{ steps.tf-plan.outputs.exitcode == 2 }}
+        id: tf-apply-string
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+        run: |
+          TERRAFORM_OUTPUT=$(terraform apply -auto-approve tfplan -no-color)
+
+          delimiter="$(openssl rand -hex 8)"
+          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+          echo "### Terraform Apply Output" >> $GITHUB_OUTPUT
+          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+          echo "" >> $GITHUB_OUTPUT
+          echo '```terraform' >> $GITHUB_OUTPUT
+          echo "$TERRAFORM_OUTPUT" >> $GITHUB_OUTPUT
+          echo '```' >> $GITHUB_OUTPUT
+          echo "</details>" >> $GITHUB_OUTPUT
+          echo "${delimiter}" >> $GITHUB_OUTPUT
+
+      - name: Publish Terraform Output to Task Summary
+        if: ${{ steps.tf-plan.outputs.exitcode == 2 }}
+        env:
+          SUMMARY: ${{ steps.tf-apply-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
